version: 2

before:
  hooks:
    - go mod tidy

builds:
  - goos:
      - linux
    goarch:
      - amd64

archives:
  - formats: ["tar.gz"]

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  groups:
    - title: "Features"
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 100
    - title: "Security updates"
      regexp: '^.*?sec(\(.+\))??!?:.+$'
      order: 150
    - title: "Bug fixes"
      regexp: '^.*?fix(\(.+\))??!?:.+$'
      order: 200
    - title: "Dependency updates"
      regexp: '^.*?deps(\(.+\))??!?:.+$'
      order: 300
    - title: Other
      order: 9999
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: sanderploegsma
    name: xrt-device-exporter
